### ISSUE TITLE
cmds/dev/8ball exports function named 'ping' and not '8ball'

### ISSUE THREAD

**Issue by Rafplayz** [Rafplayz/league-banner#2]

**Comment by Rafplayz** [comment]
oh yeah btw guys you need to fix it if the commit has an 'X'

**Comment by Rafplayz** [comment]
![image](https://user-images.githubusercontent.com/60671867/162789583-8282f7bc-7024-4682-9066-169b788e7ad3.png)

**Comment by VJ9X** [comment]
what?

**Comment by Rafplayz** [comment]
i finished it already you're late
